In [256]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,SVR

In [257]:
df = pd.read_csv(r'C:\Users\dell\Downloads\clean_loan_data (1).csv')

In [258]:
df

,Unnamed: 0,name,income,credit_score,loan_amount,years_employed,loan_approved
0,0,0,113810,389,39698,27,1
1,1,1,44592,729,15446,28,1
2,2,2,33278,584,11189,13,1
3,3,3,127196,344,48823,29,1
4,4,4,66048,496,47174,4,1
...,...,...,...,...,...,...,...
1995,1995,1995,92163,770,12251,13,2
1996,1996,1996,38799,635,48259,17,1
1997,1997,1997,41957,763,16752,5,2
1998,1998,1998,139022,360,24031,35,1
1999,1999,1999,41188,482,31397,6,1

In [259]:
df.drop(["Unnamed: 0",	"name"],axis=1,inplace=True)

In [260]:
x = df.drop("loan_approved",axis=1)

In [261]:
y= df[['loan_approved']]

In [262]:
y['loan_approved'].value_counts()

loan_approved
1    1121
2     879
Name: count, dtype: int64

In [263]:
x_train,x_test, y_train , y_test = train_test_split(x, y,test_size=0.2, random_state=42)
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((1600, 4), (1600, 1), (400, 4), (400, 1))

In [264]:
sv =SVC()
sv.fit(x_train, y_train)

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [265]:
print(sv.score(x_train, y_train))
print(sv.score(x_test, y_test))

0.63
0.5975

In [266]:
from sklearn.svm import SVC,SVR
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [267]:
dtc = DecisionTreeClassifier()

In [268]:
dtc =DecisionTreeClassifier(criterion='entropy')

In [269]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [270]:
y_pred = dtc.predict(x_test)

In [271]:
x_test

      income  credit_score  loan_amount  years_employed
1860  130290           447        16496              10
353    54050           808        10217              21
1333  105529           698        32169              35
905    74057           648         6627              20
1289   39359           802        12388              30
...      ...           ...          ...             ...
965   139999           402        49121              24
1284   49528           584        47618               9
1739  124924           331         6481              20
261    64741           742        13172              37
535    64335           696        13443              33

[400 rows x 4 columns]

In [272]:
dtc.predict([[130290,	447,	16496,	10]])

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [273]:
print(dtc.score(x_train, y_train))
print(dtc.score(x_test, y_test))

1.0
0.96

In [274]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

|Topic|	Real-World Example|
|-------------|-------------------------------------|
|Decorators|	In a FastAPI application, decorators like @app.get("/users") define API routes.|
|Generators|	Reading a 10GB log file line by line without loading the entire file into memory.|
|Iterators|	Processing records from a database one at a time.|
|Lambda Functions|	Sorting products by price in an e-commerce website.|
|List Comprehensions|	Creating a list of cleaned customer names from raw data.|
|Multithreading|	Downloading multiple files simultaneously.|
|Multiprocessing|	Training Machine Learning models using multiple CPU cores.|
|Asyncio|	Handling thousands of API requests in a chatbot or web server.|
|Context Managers|	Automatically closing database connections and files|
|Exception Handling|	Preventing an application from crashing when an API is unavailable.|
|Type Hinting|	Making large enterprise codebases easier to maintain.|
|Design Patterns|	Building scalable software |

### Model Evaluation Techniques
* Model Evaluation Techniques are used to measure how well a Machine learning model performs on unseen data.

|Actual/Predicted| Postive | Negative|
|-----------------|---------|----------|
|Postive|TP      |FN|
|Negative| FP | TN|

In [275]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[211,   6],
       [ 10, 173]])

|AUC Score| Performance|
|-----------|--------------|
|1.0   |  Perfect Model|
|0.9-0.99|Excellent|
|0.8|Good|
|0.7-0.79|Fair|
|0.5|Random Guessing|
|<0.5|Worse than Random|

### Classification Evalution Metrices
* A. Accuracy
* Measure the percentage of correct predictions.
* Accurancy = Correct Predictions/Total Predictions

#### Example:
#### Total samples = 100
#### Correct predictions = 90

#### Accurancy =  90%


* B. Precision
out of all predicted positives, how many are actually positive.

*  TP/TP+FP

TP/TP+FN>>>>>>>recall >> out of all actual positives,how many were correctly identified.

* fi-score Balance between precision and recall. >>> 2 x (precision x recall)/ (precision + recall)

|Metric|	Description|
|------------|---------------------------------|
|Accuracy	|Percentage of correct predictions.|
|Precision	|Out of all predicted positives, how many are actually positive.|
|Recall	|Out of all actual positives, how many were correctly identified.|
|F1-Score|	Balance between Precision and Recall.|
|ROC-AUC|	Measures the model's ability to distinguish between classes.|
|Confusion Matrix|	Shows TP, TN, FP, and FN predictions|

In [276]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.95      0.97      0.96       217
           2       0.97      0.95      0.96       183

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400

### mean square error

In [277]:
# mse
from sklearn.metrics import mean_squared_error as mse 
mse(y_test, y_pred)

0.04

In [278]:
from sklearn.datasets import fetch_california_housing

In [279]:
x,y = fetch_california_housing(return_X_y=True)

In [280]:
x

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [281]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [282]:
# x_train, x_test,  y_train , y_test =train_test_split(x , y ,test_size=0.2, random_state=42)
# x_train.shape, y_train.shape , x_test.shape, y_test.shape

In [283]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeClassifier()
dtr.fit(x_train, y_train)

DecisionTreeClassifier()

In [284]:
dtr.score(x_train, y_train)

1.0

In [285]:
dtr.score(x_test,y_test)

0.96

In [286]:
y_pred = dtr.predict(x_test)

In [287]:
y_pred

array([1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2,
       2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1,
       2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1,
       1, 2, 2, 2])

In [288]:
import numpy as np 
np.sqrt(25)

np.float64(5.0)

In [289]:
# mse mae 
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("mean_squared_error:- ",mean_squared_error(y_test, y_pred))
print("mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

mean_squared_error:-  0.04
mean_absolute_error:- 0.04

In [290]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
rmse

np.float64(0.2)

In [291]:
from sklearn.datasets import load_breast_cancer
x , y = load_breast_cancer(return_X_y=True)

In [292]:
from sklearn.model_selection import train_test_split

In [293]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [294]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()

In [295]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [296]:
x_train

array([[9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, ..., 2.903e-01, 4.098e-01,
        1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]], shape=(455, 30))

In [297]:
y_pred = knn.predict(x_test)

In [299]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [300]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [ ]:
print(knn.score(x_train,y_train))

0.9406593406593406

In [ ]:
print(knn.score(x_test,y_test))

0.956140350877193

#### Without hyper parameter

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [ ]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
print(rfc.score(x_test,y_test))

0.9649122807017544

In [ ]:
print(rfc.score(x_train,y_train))

1.0

### With hyper parameter

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=1, min_samples_split=2)

In [ ]:
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=1, n_estimators=150)

In [ ]:
print(rfc.score(x_test,y_test))
print(rfc.score(x_train,y_train))

0.956140350877193
0.9340659340659341

In [302]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 1,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 150,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}