In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\dell\Downloads\clean_bike_data.csv")
df

,Unnamed: 0,price,city,kms_driven,owner,age,power,brand
0,0,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,1,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,2,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,3,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,4,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
7319,9362,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
7320,9369,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
7321,9370,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
7322,9371,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
7323,9372,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [4]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7319    False
7320    False
7321    False
7322    False
7323    False
Length: 7324, dtype: bool

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [7]:
df.drop("city",axis=1,inplace=True)

In [8]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [9]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
7319   25000.0     48587.0  First Owner  8.0  150.0             Hero
7320   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
7321  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
7322  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
7323   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [10]:
df.duplicated().sum()

np.int64(18)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
7319   25000.0     48587.0  First Owner  8.0  150.0             Hero
7320   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
7321  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
7322  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
7323   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [13]:
owner_dict= {'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
df['owner']=df['owner'].map(owner_dict) 
# map was using to do mapping

In [14]:
brand_dict={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23}
df["brand"] =df["brand"].map(brand_dict)

In [15]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      1
1     119900.0     11000.0      1  4.0  350.0      2
2     600000.0       110.0      1  8.0  675.0      3
3      65000.0     16329.0      1  4.0  180.0      1
4      80000.0     10000.0      1  3.0  150.0      4
...        ...         ...    ...  ...    ...    ...
7319   25000.0     48587.0      1  8.0  150.0      6
7320   35000.0     60000.0      1  9.0  220.0      7
7321  450000.0      3430.0      1  4.0  750.0     15
7322  139000.0     21300.0      1  4.0  400.0      7
7323   80000.0      7127.0      1  5.0  220.0      7

[7306 rows x 6 columns]

### Machine learning 
* Machine Learning is a method of teaching computers to learn from data and improve their performance automatically.


| Type                     | Description                          |
| ------------------------ | ------------------------------------ |
| Supervised Learning      | Learns from labeled data             |
| Unsupervised Learning    | Learns from unlabeled data           |
| Semi-Supervised Learning | Uses both labeled and unlabeled data |
| Reinforcement Learning   | Learns through rewards and penalties |

Labeled Data                 | Unlabeled Data                   |
| ---------------------------- | -------------------------------- |
| Has correct answers (labels) | No correct answers               |
| Used in Supervised Learning  | Used in Unsupervised Learning    |
| Easier to train models       | Used to discover hidden patterns |
| Example: House Price Dataset | Example: Customer Purchase Data

Classification and Regression are two major types of supervised machine learning tasks.

1. Classification

Classification is used when the output is a category or label.

Examples:

Email → Spam or Not Spam
Image → Cat, Dog, or Bird
Patient → Has Disease or No Disease

Input: Features (e.g., age, income, symptoms)
Output: Discrete classes or categories

Example:

Study Hours	Pass/Fail
2	Fail
8	Pass

The model learns to predict whether a student will Pass or Fail.

2. Regression

Regression is used when the output is a continuous numerical value.

Examples:

Predict house price
Forecast temperature
Estimate sales revenue

Input: Features (e.g., house size, location)
Output: A number

Example:

House Size (sq ft)	Price ($)
1000	150,000
2000	300,000

The model learns to predict the price of a house.

| Key Difference  | in |
|-------------------------------------|-------------------------------------|
| Classification   | Regression |
|Predicts categories	|Predicts numbers|
|Output is discrete	|Output is continuous|
|Example: Spam/Not Spam	|Example: House Price|
|Algorithms: Logistic Regression, Decision Trees, SVM	|Algorithms: Linear Regression, Random Forest Regressor|


Simple Rule
If the answer is "Which class?" → Classification
If the answer is "How much?" or "How many?" → Regression

In [16]:
x = df.drop("price",axis=1)
y = df[['price']]

In [17]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
7319     48587.0      1  8.0  150.0      6
7320     60000.0      1  9.0  220.0      7
7321      3430.0      1  4.0  750.0     15
7322     21300.0      1  4.0  400.0      7
7323      7127.0      1  5.0  220.0      7

[7306 rows x 5 columns]

In [18]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7319   25000.0
7320   35000.0
7321  450000.0
7322  139000.0
7323   80000.0

[7306 rows x 1 columns]

In [19]:
#pip install scikit-learn

In [20]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y ,random_state=42, test_size =0.2)

In [21]:
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((5844, 5), (5844, 1), (1462, 5), (1462, 1))

In [22]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [23]:
bike_1 = lr.predict([[17654.0,	1,	3.0,	110.0,	1]])
bike_1

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[-9742.13864087]])

In [24]:
print(lr.score(x_train, y_train))
print(lr.score(x_test, y_test))

0.7116425245703818
0.7434808272417703

In [ ]:
import joblib
joblib.dump(lr, "model.lb")
# dump function is used to save the model

['model.lb']

In [26]:
import joblib
joblib.dump(lr, "model_rfr.lb")

['model_rfr.lb']

In [27]:
model =joblib.load('model.lb')

In [28]:
model.predict([[11000.0,	1,	4.0,	350.0,	2]])

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[134183.62638317]])

In [29]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7319   25000.0
7320   35000.0
7321  450000.0
7322  139000.0
7323   80000.0

[7306 rows x 1 columns]

In [31]:
from sklearn.ensemble import RandomForestRegressor
lr =RandomForestRegressor()
lr.fit(x_train, y_train)

c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()