In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\dell\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\dell\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 2.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.9 MB 2.0 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.9 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.9 MB 2.3 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.9 MB 2.2 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.9 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.9 MB 2.2 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.9 MB 2.2 MB/s eta 0:00:03
   ---------------- ----------------------- 4.2/9.9 MB 2.1 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.9 MB 2.1 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 2.1 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 2.2 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/9.9 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.5 MB/s  0:00:04
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

In [67]:
print("hello")

hello

## Pandas
Pandas is a popular open-source Python library for data manipulation and analysis. It provides powerful data structures and tools for working with structured data such as tables, CSV files, spreadsheets, SQL results, and time series.

Key data structures:
##### Series → 1-dimensional labeled array
##### DataFrame → 2-dimensional table (most commonly used)

In [ ]:
import os
import numpy as np
import pandas as pd

In [69]:
df = pd.read_csv(r"C:\Users\dell\Desktop\Data science\Pandas\Used_Bikes (1).csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [70]:
df.head()   # for taking first five rows and it give default 5 rows

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [71]:
df.head(10)  # it will give rows that we eant

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [72]:
df.tail()   # give 5 rows default from last

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [73]:
df.tail(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [74]:
df.info()   # give infoormation of dataset

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [75]:
df.columns  # give all columns and it is keyword

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [76]:
df['bike_name']   # give the particular column

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [77]:
df[['brand']]   # give column in proper format by using double square brackets

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [78]:
df[['price','brand']]

          price          brand
0       35000.0            TVS
1      119900.0  Royal Enfield
2      600000.0        Triumph
3       65000.0            TVS
4       80000.0         Yamaha
...         ...            ...
32643   39000.0           Hero
32644   30000.0            TVS
32645   60000.0          Bajaj
32646   15600.0           Hero
32647   22000.0          Bajaj

[32648 rows x 2 columns]

In [79]:
df["brand"].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [80]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [81]:
df['brand'].nunique()  ## number of unique value

23

In [82]:
df["brand"].value_counts()   # it will give which brand have how many bikes

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [83]:
df.duplicated().sum()

np.int64(25324)

In [84]:
df.drop_duplicates()  # this not permently delete the duplicates

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [85]:
df.drop_duplicates(inplace=True)  # this will delete all duplicates permaently

In [86]:
df.duplicated().sum()

np.int64(0)

In [87]:
df.isnull()  # check null values present in the data

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [88]:
df.isnull().sum()  # to get the sum of all null values

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [89]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [90]:
# y = mx+c

df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
 owner_dict ={
     'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
}

In [92]:
# df['owner']=df['owner'].map(owner_dict) # map is used for mapping
# df

In [93]:
#df.drop("city",axis=1,inplace=True)
#df

In [94]:
##df.drop(["price","bike_name"],axis=1,inplace=True)
#df

In [95]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [96]:
obj_val = df.select_dtypes(include='O')

C:\Users\dell\AppData\Local\Temp\ipykernel_2384\2567366858.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val = df.select_dtypes(include='O')

In [97]:
num_val = df.select_dtypes(exclude='O')
num_val

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [98]:
complete_Data = pd.concat([obj_val,num_val],axis=1)
complete_Data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000.0,7127.0,5.0,220.0

In [99]:
tvs_brand= df[df["brand"]=="TVS"]  # filtering of the data
tvs_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [100]:
# # dup drop
# >null drop
# >string to integer
# unncessary column drop

In [101]:
tvs_brand['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner']
Length: 3, dtype: str

In [ ]:
tvs_first = tvs_brand[tvs_brand['owner']=='First Owner']
tvs_first

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [105]:
tvs_age=tvs_first[tvs_first['age']<=2]
tvs_age

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [ ]:
df['age']

In [106]:
tvs_kms= tvs_age[tvs_age['kms_driven']<=20000]
tvs_age

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000.0,Hyderabad,16000.0,First Owner,2.0,160.0,TVS
360,TVS Apache RTR 160 4V Disc,78700.0,Rudrapur,3710.0,First Owner,2.0,160.0,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500.0,Delhi,10000.0,First Owner,2.0,200.0,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000.0,Delhi,7000.0,First Owner,2.0,160.0,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000.0,Gurgaon,7000.0,First Owner,2.0,160.0,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800.0,Delhi,1050.0,First Owner,2.0,160.0,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000.0,Delhi,3000.0,First Owner,2.0,160.0,TVS
757,TVS Apache RTR 160 4V Disc,74700.0,Gautam Buddha Nagar,20194.0,First Owner,2.0,160.0,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500.0,Bangalore,2500.0,First Owner,2.0,200.0,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000.0,Bangalore,1300.0,First Owner,1.0,200.0,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000.0,Jaipur,749.0,First Owner,1.0,160.0,TVS
1171,TVS Apache RR310,200000.0,Mumbai,4400.0,First Owner,2.0,310.0,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000.0,Hyderabad,530.0,First Owner,2.0,200.0,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000.0,Delhi,8000.0,First Owner,2.0,160.0,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000.0,Chennai,3100.0,First Owner,2.0,200.0,TVS
1712,TVS Apache RR310 Slipper Clutch,224000.0,Vadodara,3900.0,First Owner,2.0,310.0,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500.0,Delhi,2800.0,First Owner,2.0,200.0,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135.0,Delhi,2800.0,First Owner,2.0,160.0,TVS
1802,TVS Apache RTR 180cc,88000.0,Gurgaon,900.0,First Owner,2.0,180.0,TVS
2325,TVS Apache RTR 200 4V ABS,92000.0,Mumbai,4500.0,First Owner,2.0,200.0,TVS
2360,TVS Victor 110cc Disc SBT,54000.0,Delhi,6000.0,First Owner,2.0,110.0,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000.0,Delhi,11496.0,First Owner,2.0,160.0,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000.0,Ahmedabad,893.0,First Owner,2.0,160.0,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000.0,Bangalore,52198.0,First Owner,2.0,160.0,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000.0,Mumbai,6821.0,First Owner,2.0,160.0,TVS
3440,TVS Apache RTR 160 4V Disc,92000.0,Mumbai,14289.0,First Owner,2.0,160.0,TVS
4251,TVS Star City Plus 110cc,51000.0,Ahmedabad,12000.0,First Owner,2.0,110.0,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000.0,Ghaziabad,2672.0,First Owner,2.0,160.0,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000.0,Delhi,1890.0,First Owner,2.0,200.0,TVS
5510,TVS Apache RTR 180cc,90000.0,Ghaziabad,3095.0,First Owner,2.0,180.0,TVS
5557,TVS Apache RTR 200 4V FI,102000.0,Thane,8120.0,First Owner,2.0,200.0,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000.0,Bangalore,4000.0,First Owner,2.0,200.0,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700.0,Delhi,900.0,First Owner,2.0,160.0,TVS
6058,TVS Apache RR310,220000.0,Noida,5432.0,First Owner,2.0,310.0,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000.0,Faridabad,15228.0,First Owner,2.0,160.0,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000.0,Mumbai,7157.0,First Owner,2.0,200.0,TVS
7055,TVS Sport 100cc,46000.0,Faridabad,6222.0,First Owner,2.0,100.0,TVS
7311,TVS Apache RTR 180cc,70000.0,Jaipur,207102.0,First Owner,2.0,180.0,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000.0,Mumbai,4442.0,First Owner,2.0,200.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [107]:
Royal_brand = df[df["brand"]=="Royal Enfield"]  # filtering of the data
Royal_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,First Owner,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,First Owner,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield

In [108]:
Royal_owner= Royal_brand[Royal_brand['owner']=='First Owner']
Royal_owner

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,First Owner,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,First Owner,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield

In [109]:
Royal_age = Royal_brand[Royal_brand['age']<=2]
Royal_age

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [112]:
Royal_kms = Royal_age[Royal_age["kms_driven"]<=10000]
Royal_kms

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
277,Royal Enfield Interceptor 650cc,280000.0,Bangalore,1500.0,First Owner,2.0,650.0,Royal Enfield
394,Royal Enfield Classic Gunmetal Grey 350cc ABS,160000.0,Mumbai,7500.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
850,Royal Enfield Himalayan 410cc Fi ABS,180000.0,Guwahati,200.0,First Owner,2.0,410.0,Royal Enfield
871,Royal Enfield Thunderbird 350cc ABS,175000.0,Delhi,2382.0,First Owner,2.0,350.0,Royal Enfield
962,Royal Enfield Thunderbird X 350cc ABS,155000.0,Vadodara,1650.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1251,Royal Enfield Interceptor 650cc,250000.0,Silchar,920.0,First Owner,2.0,650.0,Royal Enfield
1365,Royal Enfield Bullet 500cc,172000.0,Delhi,8000.0,First Owner,2.0,500.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
1760,Royal Enfield Thunderbird X 350cc ABS,172000.0,Delhi,3800.0,First Owner,2.0,350.0,Royal Enfield
1796,Royal Enfield Himalayan 410cc Fi ABS,166000.0,Guwahati,250.0,First Owner,2.0,410.0,Royal Enfield
1931,Royal Enfield Interceptor 650cc,270000.0,Ahmedabad,6500.0,First Owner,2.0,650.0,Royal Enfield
1955,Royal Enfield Bullet 500cc,164100.0,Delhi,8000.0,First Owner,2.0,500.0,Royal Enfield
2074,Royal Enfield Classic 500cc,181200.0,Baripara,5000.0,First Owner,2.0,500.0,Royal Enfield
2228,Royal Enfield Interceptor 650cc,280000.0,Mumbai,5000.0,First Owner,2.0,650.0,Royal Enfield
2283,Royal Enfield Classic 350cc Dual Disc,156000.0,Pune,6517.0,First Owner,2.0,350.0,Royal Enfield
2332,Royal Enfield Interceptor 650cc,265000.0,Delhi,8500.0,First Owner,2.0,650.0,Royal Enfield
2625,Royal Enfield Classic 350cc Signals Edition,160000.0,Bangalore,10000.0,First Owner,2.0,350.0,Royal Enfield
2735,Royal Enfield Classic Gunmetal Grey 350cc ABS,167000.0,Farukhabad,2500.0,First Owner,2.0,350.0,Royal Enfield
2929,Royal Enfield Himalayan 410cc Fi ABS,184000.0,Bardhaman,1380.0,First Owner,2.0,410.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
3084,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
3089,Royal Enfield Classic Desert Storm 500cc Dual ...,239000.0,Mumbai,1264.0,First Owner,2.0,500.0,Royal Enfield
3166,Royal Enfield Thunderbird X 350cc ABS,160000.0,Delhi,1189.0,First Owner,2.0,350.0,Royal Enfield
4544,Royal Enfield Thunderbird 350cc ABS,155000.0,Navi Mumbai,2900.0,First Owner,2.0,350.0,Royal Enfield
4727,Royal Enfield Himalayan 410cc Fi ABS,172000.0,Hyderabad,3165.0,First Owner,2.0,410.0,Royal Enfield
4912,Royal Enfield Continental GT 650cc,285000.0,Hyderabad,4500.0,First Owner,2.0,650.0,Royal Enfield
5133,Royal Enfield Thunderbird X 350cc ABS,170000.0,Gurgaon,500.0,First Owner,2.0,350.0,Royal Enfield
5472,Royal Enfield Classic 350cc Signals Edition,165000.0,Faridabad,2791.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5703,Royal Enfield Himalayan 410cc Fi ABS,194000.0,Thane,844.0,First Owner,2.0,410.0,Royal Enfield
5822,Royal Enfield Classic 350cc Signals Edition,170000.0,Ahmedabad,7000.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6022,Royal Enfield Classic Gunmetal Grey 350cc ABS,161100.0,Guwahati,1753.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6283,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [115]:
Royal_price= Royal_kms[Royal_kms['price']<=150000]
Royal_price

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield

In [119]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<=150000) &(df['kms_driven']<=50000)]
# if give condition not in data like 3 owner not not in data not show table

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
479,Royal Enfield Classic 350cc,150000.0,Delhi,4000.0,First Owner,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,First Owner,2.0,350.0,Royal Enfield
1203,Royal Enfield Classic Gunmetal Grey 350cc ABS,150000.0,Bardhaman,1800.0,First Owner,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,First Owner,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,First Owner,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,First Owner,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,First Owner,2.0,350.0,Royal Enfield
5495,Royal Enfield Classic 350cc,150000.0,Kota,1947.0,First Owner,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,First Owner,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,First Owner,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,First Owner,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,First Owner,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,First Owner,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,First Owner,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield

In [ ]:
df.query("brand=='Royal Enfield' and age <=2")
# use query for conditions because it is shorter

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,First Owner,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [ ]:
df

In [122]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [123]:
df.duplicated().sum()

np.int64(18)

In [124]:
df.drop_duplicates()

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7306 rows x 6 columns]

In [ ]:
#df.dropna(inplace=True)

In [129]:
x =df.drop('price',axis=1)
x

      kms_driven        owner  age  power            brand
0        17654.0  First Owner  3.0  110.0              TVS
1        11000.0  First Owner  4.0  350.0    Royal Enfield
2          110.0  First Owner  8.0  675.0          Triumph
3        16329.0  First Owner  4.0  180.0              TVS
4        10000.0  First Owner  3.0  150.0           Yamaha
...          ...          ...  ...    ...              ...
9362     48587.0  First Owner  8.0  150.0             Hero
9369     60000.0  First Owner  9.0  220.0            Bajaj
9370      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371     21300.0  First Owner  4.0  400.0            Bajaj
9372      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 5 columns]

In [127]:
y =df[['price']]

In [128]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [5]:
# y =mx+c this is linear regression